version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
  nginx-proxy-acme:
    depends_on:
      - "nginx-proxy"
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=lion.su@mail.utoronto.ca
  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/proj360-frontend
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=project360.me
      - LETSENCRYPT_HOST=project360.me
  backend:
    image: ghcr.io/uoft-utsc-cs-sandbox/proj360-backend
    container_name: backend
    restart: always
    expose:
      - 5000
    environment:
      - VIRTUAL_HOST=api.project360.me
      - LETSENCRYPT_HOST=api.project360.me
